import type { Activity } from './activity.ts'

export const activities: Activity[] = [
  {
    id: 1,
    name: 'Walk',
    description: 'A neighborhood walk, walk the trail, go the Greenbelt, anywhere you want to go.',
    energy: 'medium',
    moods: ['chill'],
    company: 'any',
    setting: 'outdoor',
    movement: 'light',
    cost: 'free',
    needsDaylight: false,
    weather: ['clear', 'cold'],
  },
  {
    id: 2,
    name: 'Run',
    description: 'Get out and run while it still feels good outside.',
    energy: 'high',
    moods: ['adventurous'],
    company: 'solo',
    setting: 'outdoor',
    movement: 'active',
    cost: 'free',
    needsDaylight: false,
    weather: ['clear', 'cold'],
  },
  {
    id: 3,
    name: 'Pilates',
    description: 'Go to Todds and chill or hit solidcore and sweat your ass off.',
    energy: 'medium',
    moods: ['chill'],
    company: 'solo',
    setting: 'indoor',
    movement: 'active',
    cost: 'low',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 4,
    name: 'Pool',
    description: 'Take your book and read in the water.',
    energy: 'medium',
    moods: ['playful'],
    company: 'any',
    setting: 'outdoor',
    movement: 'active',
    cost: 'low',
    needsDaylight: true,
    weather: ['clear', 'hot'],
  },
  {
    id: 5,
    name: 'Barton Springs',
    description: 'Cold water, a big lawn, and a full afternoon outside.',
    energy: 'high',
    moods: ['adventurous', 'playful'],
    company: 'any',
    setting: 'outdoor',
    movement: 'active',
    cost: 'low',
    needsDaylight: true,
    weather: ['clear', 'hot'],
  },
  {
    id: 6,
    name: 'Deep Eddy',
    description: 'Dip in the pool and then grab a burger and beer at Pool Burger.',
    energy: 'medium',
    moods: ['chill', 'playful'],
    company: 'any',
    setting: 'outdoor',
    movement: 'light',
    cost: 'low',
    needsDaylight: true,
    weather: ['clear', 'hot'],
  },
  {
    id: 7,
    name: 'Patio hang',
    description: 'Sit outside with a drink and watch the sky change colors.',
    energy: 'low',
    moods: ['social', 'chill'],
    company: 'any',
    setting: 'outdoor',
    movement: 'still',
    cost: 'low',
    needsDaylight: false,
    weather: ['clear'],
  },
  {
    id: 8,
    name: 'Trivia',
    description: 'General or specialized, find some trivia tonight and be silly with your friends.',
    energy: 'medium',
    moods: ['social', 'playful'],
    company: 'friends',
    setting: 'indoor',
    movement: 'still',
    cost: 'low',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 9,
    name: 'Live music',
    description: 'You live in Austin, go listen to some live music.',
    energy: 'medium',
    moods: ['social', 'adventurous'],
    company: 'friends',
    setting: 'indoor',
    movement: 'still',
    cost: 'low',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 10,
    name: 'Hang out with friends',
    description: 'Invite some friends over for a movie night, game night, or just to hang out.',
    energy: 'low',
    moods: ['social', 'cozy'],
    company: 'friends',
    setting: 'either',
    movement: 'still',
    cost: 'free',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 11,
    name: "Grill on Eric's roof",
    description: 'Grill out while sun sets and have dessert in the pool.',
    energy: 'medium',
    moods: ['social', 'cozy'],
    company: 'date',
    setting: 'outdoor',
    movement: 'light',
    cost: 'low',
    needsDaylight: false,
    weather: ['clear'],
  },
  {
    id: 12,
    name: 'Date night',
    description: 'Get gussied up and go somewhere flirty.',
    energy: 'medium',
    moods: ['social', 'cozy'],
    company: 'date',
    setting: 'either',
    movement: 'still',
    cost: 'splurge',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 13,
    name: 'Sunset drinks and a walk',
    description: 'Catch the sunset then walk somewhere for a drink.',
    energy: 'medium',
    moods: ['chill', 'playful'],
    company: 'date',
    setting: 'outdoor',
    movement: 'light',
    cost: 'low',
    needsDaylight: true,
    weather: ['clear'],
  },
  {
    id: 14,
    name: 'Movie',
    description: 'Pick something and be done deciding for the night.',
    energy: 'low',
    moods: ['chill', 'cozy'],
    company: 'any',
    setting: 'indoor',
    movement: 'still',
    cost: 'low',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 15,
    name: 'Reading',
    description: 'Stay in with a book and let the night stay quiet. Bonus points for a fire or patio lounge.',
    energy: 'low',
    moods: ['chill', 'cozy'],
    company: 'solo',
    setting: 'indoor',
    movement: 'still',
    cost: 'free',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 16,
    name: 'Craft night',
    description: 'Make something small at home with your hands busy. Invite someone to join if you want company.',
    energy: 'low',
    moods: ['cozy', 'playful'],
    company: 'any',
    setting: 'indoor',
    movement: 'light',
    cost: 'low',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 17,
    name: 'Early bedtime',
    description: 'Seems like you could use some rest dog, go to sleep early.',
    energy: 'low',
    moods: ['cozy', 'chill'],
    company: 'solo',
    setting: 'indoor',
    movement: 'still',
    cost: 'free',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
]
