import type { Activity } from './activity.ts'

export const activities: Activity[] = [
  {
    id: 1,
    name: 'Walk',
    description: 'A neighborhood walk with no plan attached.',
    energy: 'medium',
    moods: ['chill'],
    company: 'any',
    setting: 'outdoor',
    movement: 'light',
    cost: 'free',
    needsDaylight: false,
    weather: ['clear', 'cold'],
  },
  {
    id: 2,
    name: 'Run',
    description: 'Get out and run while it still feels good outside.',
    energy: 'high',
    moods: ['adventurous'],
    company: 'solo',
    setting: 'outdoor',
    movement: 'active',
    cost: 'free',
    needsDaylight: false,
    weather: ['clear', 'cold'],
  },
  {
    id: 3,
    name: 'Pilates',
    description: 'A class that uses the energy without wrecking the night.',
    energy: 'medium',
    moods: ['chill'],
    company: 'solo',
    setting: 'indoor',
    movement: 'active',
    cost: 'low',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 4,
    name: 'Pool',
    description: 'Swim, then stay in the water longer than you meant to.',
    energy: 'medium',
    moods: ['playful'],
    company: 'any',
    setting: 'outdoor',
    movement: 'active',
    cost: 'low',
    needsDaylight: true,
    weather: ['clear', 'hot'],
  },
  {
    id: 5,
    name: 'Barton Springs',
    description: 'Cold water, a big lawn, and a full afternoon outside.',
    energy: 'high',
    moods: ['adventurous', 'playful'],
    company: 'any',
    setting: 'outdoor',
    movement: 'active',
    cost: 'low',
    needsDaylight: true,
    weather: ['clear', 'hot'],
  },
  {
    id: 6,
    name: 'Deep Eddy',
    description: 'An easier pool day, close by, with room to float.',
    energy: 'medium',
    moods: ['chill', 'playful'],
    company: 'any',
    setting: 'outdoor',
    movement: 'light',
    cost: 'low',
    needsDaylight: true,
    weather: ['clear', 'hot'],
  },
  {
    id: 7,
    name: 'Patio hang',
    description: 'Sit outside with a drink and let the evening move slowly.',
    energy: 'low',
    moods: ['social', 'chill'],
    company: 'any',
    setting: 'outdoor',
    movement: 'still',
    cost: 'low',
    needsDaylight: false,
    weather: ['clear'],
  },
  {
    id: 8,
    name: 'Trivia',
    description: 'A team, a table, and something to pay attention to.',
    energy: 'medium',
    moods: ['social', 'playful'],
    company: 'friends',
    setting: 'indoor',
    movement: 'still',
    cost: 'low',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 9,
    name: 'Live music',
    description: 'Go hear someone play instead of staying in.',
    energy: 'medium',
    moods: ['social', 'adventurous'],
    company: 'friends',
    setting: 'indoor',
    movement: 'still',
    cost: 'low',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 10,
    name: 'Hang out with friends',
    description: 'Be with people, without turning it into an event.',
    energy: 'low',
    moods: ['social', 'cozy'],
    company: 'friends',
    setting: 'either',
    movement: 'still',
    cost: 'free',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 11,
    name: "Grill on Eric's roof",
    description: 'Cook upstairs and stay out while the city cools off.',
    energy: 'medium',
    moods: ['social', 'cozy'],
    company: 'date',
    setting: 'outdoor',
    movement: 'light',
    cost: 'low',
    needsDaylight: false,
    weather: ['clear'],
  },
  {
    id: 12,
    name: 'Date night',
    description: 'Get dressed up a little and go somewhere together.',
    energy: 'medium',
    moods: ['social', 'cozy'],
    company: 'date',
    setting: 'either',
    movement: 'still',
    cost: 'splurge',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 13,
    name: 'Sunset drinks and a walk',
    description: 'Catch the sunset, then walk somewhere for a drink.',
    energy: 'medium',
    moods: ['chill', 'playful'],
    company: 'date',
    setting: 'outdoor',
    movement: 'light',
    cost: 'low',
    needsDaylight: true,
    weather: ['clear'],
  },
  {
    id: 14,
    name: 'Movie',
    description: 'Pick something and be done deciding for the night.',
    energy: 'low',
    moods: ['chill', 'cozy'],
    company: 'any',
    setting: 'indoor',
    movement: 'still',
    cost: 'low',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 15,
    name: 'Reading',
    description: 'Stay in with a book and let the night stay quiet.',
    energy: 'low',
    moods: ['chill', 'cozy'],
    company: 'solo',
    setting: 'indoor',
    movement: 'still',
    cost: 'free',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 16,
    name: 'Craft night',
    description: 'Make something small at home with your hands busy.',
    energy: 'low',
    moods: ['cozy', 'playful'],
    company: 'any',
    setting: 'indoor',
    movement: 'light',
    cost: 'low',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
  {
    id: 17,
    name: 'Early bedtime',
    description: 'Call it and actually go to sleep.',
    energy: 'low',
    moods: ['cozy', 'chill'],
    company: 'solo',
    setting: 'indoor',
    movement: 'still',
    cost: 'free',
    needsDaylight: false,
    weather: ['clear', 'hot', 'cold', 'rain'],
  },
]
